### ISSUE TITLE
Does Not Build

### ISSUE THREAD

**Issue by adamnovak** [dentearl/mafTools#6]
Fails to build on GCC 4.9.0, producing this error:

```
cd mafExtractor && make all
make[1]: Entering directory `/cluster/home/anovak/build/mafTools/mafExtractor'
gcc -std=c99 -O3 -c -O3 -Wall -Werror --pedantic -funroll-loops -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -I ../../sonLib/lib -I ../inc -I ../external -I /hive/groups/recon/local/include src/mafExtractorAPI.c -o src/mafExtractorAPI.o.tmp -lm
src/mafExtractorAPI.c: In function ‘processBlockForSplice’:
src/mafExtractorAPI.c:193:23: error: variable ‘sum’ set but not used [-Werror=unused-but-set-variable]
     uint64_t len = 0, sum = 0;
                       ^
cc1: all warnings being treated as errors
make[1]: *** [src/mafExtractorAPI.o] Error 1
make[1]: Leaving directory `/cluster/home/anovak/build/mafTools/mafExtractor'
make: *** [mafExtractor.all] Error 2

```
